---
version: 20211103
settings:
  html_out: true
  console_out: true
  gpu_view: true
modules:
  t_rex_unm:
    port: 4067
    extra: ETH>BTT
    coin: ETC
    api: t_rex
    gpu_row: 4
    nodes:
      valhalla: 192.168.0.113
  phoenix:
    port: 33440
    api: phoenix
    extra: ETH
    coin: ETH
    gpu_row: 5
    nodes:
      helter: 192.168.0.111:33440
      helios: 192.168.0.116
      pedxing: 192.168.0.106
      nefarious: 192.168.0.120
      serenity: 192.168.0.104
  phoenix_unm:
    port: 33433
    extra: ETH>ETC
    coin: SHIB
    api: phoenix
    gpu_row: 3
    standalone: false
    page: 1
    nodes:
      vendetta: 192.168.0.122
  nice_hash:
    port: 18000
    extra: ETH
    coin: ETH
    api: excavator
    nodes:
      skelter: 192.168.0.112
  phoenix_unm2:
    port: 33433
    extra: ETH>SHIB
    coin: SHIB
    api: phoenix
    gpu_row: 3
    standalone: true
    page: 3
    nodes:
      vendetta: 192.168.0.122
  xmrig:
    port: 8989
    extra: XMR
    coin: XMR
    every: 12
    api: xmrig
    page: 1
    nodes:
#      valhalla: 192.168.0.113
      pedxing: 192.168.0.106
      vendetta: 192.168.0.122
  raptoreum:
    port: 4048
    extra: RTM
    coin: RTM
    every: 12
    api: cpuminer
    page: 1
    nodes:
      valhalla: 192.168.0.113
  signum_pool_miner:
    every: 180
    actual: 
    port: 0
    page: 1
    api: signum_pool_miner
    extra: signapool.notallmine.net
    capacity:
      S-39C7-CS43-QPMM-FXMJ3: 94.3727
      S-CJFF-3JYH-GMBY-D2DRX: 5.4575 
    nodes:
      S-39C7-CS43-QPMM-FXMJ3: https://signapool.notallmine.net
      S-CJFF-3JYH-GMBY-D2DRX: https://signapool.notallmine.net
    thresholds:
      S-39C7-CS43-QPMM-FXMJ3:
        physical_capacity:
        - "<"
        - yellow
        - 90.7341
      S-CJFF-3JYH-GMBY-D2DRX:
        physical_capacity:
        - "<"
        - yellow
        - 3.6383
  signum_pool_view:
    every: 180
    port: 0
    record_count: 50
    show_block_winners: true
    api: signum_pool_view
    page: 2
    extra:
    nodes:
      Signapool NotAllMine: https://signapool.notallmine.net
    highlight_nodes:
      S-39C7-CS43-QPMM-FXMJ3
      S-CJFF-3JYH-GMBY-D2DRX 
