---
version: 20211103
settings:
  html_out: true
  console_out: true
  gpu_view: true
modules:
  t_rex_unm:
    port: 4067
    extra: ETH>BTT
    coin: ETH
    api: t_rex
    gpu_row: 4
    nodes:
      valhalla: 192.168.0.113
  phoenix:
    port: 33440
    api: phoenix
    extra: ETH
    coin: ETH
    gpu_row: 5
    nodes:
      helios: 192.168.0.116:33440
      pedxing: 192.168.0.106
      nefarious: 192.168.0.120
      serenity: 192.168.0.104
  phoenix_unm:
    port: 33433
    extra: ETH>HOT
    coin: ETH
    api: phoenix
    gpu_row: 3
    standalone: false
    page: 1
    nodes:
      vendetta: 192.168.0.122
  nice_hash:
    port: 18000
    extra: ETH
    coin: ETH
    api: excavator
    nodes:
      helter: 192.168.0.111
      skelter: 192.168.0.112
  xmrig:
    port: 8989
    extra: XMR
    coin: XMR
    every: 12
    api: xmrig
    page: 1
    nodes:
      pedxing: 192.168.0.106
      vendetta: 192.168.0.122
  raptoreum:
    port: 4048
    extra: RTM
    coin: RTM
    every: 12
    api: cpuminer
    page: 1
    nodes:
      valhalla: 192.168.0.113
  smi_rest1:
    port: 30999
    extra:
    every: 12
    api: smi_rest
    page: 5
    nodes:
      valhalla: 192.168.0.113
  signum_pool_miner:
    every: 180
    actual:
    port: 0
    page: 1
    api: signum_pool_miner
    extra: signapool.notallmine.net
    capacity:
      S-39C7-CS43-QPMM-FXMJ3: 94.3727
      S-CJFF-3JYH-GMBY-D2DRX: 5.4575
    nodes:
      S-39C7-CS43-QPMM-FXMJ3: https://signapool.notallmine.net
      S-CJFF-3JYH-GMBY-D2DRX: https://signapool.notallmine.net
  signum_pool_view:
    every: 180
    port: 0
    record_count: 15
    show_block_winners: true
    api: signum_pool_view
    page: 2
    extra:
    nodes:
      Signapool NotAllMine: https://signapool.notallmine.net
    highlight_nodes: S-39C7-CS43-QPMM-FXMJ3 S-CJFF-3JYH-GMBY-D2DRX
  unmineable:
    every: 300
    api: unmineable
    page: 2
    nodes:
      BTT: TPMFKMtUYsEDdqEvLhZtGCNNXJX2Hbp5W5:BTT
      HOT: 0xBf8f8F0d781DeEA687544dECb7f422066686d075:HOT
      XMR: 83waEwQgGsVeZfkavB8PBa6rtQBx6pgEuYx2BzYwj5LYRxpr4nir4RzTkAq2zDK2BLbWVfk1bd6NMMGUQeGuWoz37tWNEsg:XMR
  flock_pool:
    every: 300
    api: flock_pool
    page: 2
    nodes:
      RTM: RKH9fDmKabTowQhYoQQHbwe8cppXDi6Qrm
html_out: true
base_line_frequency: 8
pages:
    1: Overview
    2: Pools
    3: Standalone Test
    4: Pools
    5: GPUs
plugins:
  conemu:
    standalone_fontsize: 20
  smi_rest_start:
    port: 30999
  gpu_caps_viewer:
    path: "./"
    frequency: 12
  what_to_mine:
    lifespan: 300
