# Table colors
$color_divider  = :magenta,:dim
$color_header   = :green,:on_blue
$color_row      = :white,:dim
$color_warn  = :bright_yellow
$color_alert = :bright_red
$color_ok    = :bright_green
$color_row_even = :cyan
$color_row_odd  = :green
$color_standalone_title = :white,:on_blue
